import '@superclean-workspace/shared/styles';
import { ThemeProvider } from 'next-themes';
import { Plus_Jakarta_Sans } from "next/font/google";


export const metadata = {
  title: 'Welcome to mitra-app',
  description: 'Generated by create-nx-workspace',
};
const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className='scroll-smooth'>
      <body
        className={`${jakartaSans.className} antialiased md:flex `}
      >
        <ThemeProvider enableSystem={true} defaultTheme='system' attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
