import '@superclean-workspace/shared/styles';
import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: 'Welcome to mitra-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className='scroll-smooth'>
      <body>
        <ThemeProvider enableSystem={true} defaultTheme='system' attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
