import ProtectedLayout from "@shared/components/ProtectedLayout";
import '@superclean-workspace/shared/styles';
import { NavigationBar } from "libs/shared/src/components/mitra/navigation-bar";
import { Toaster } from "libs/ui-components/src/components/ui/toaster";
import { ThemeProvider } from 'next-themes';
import { Plus_Jakarta_Sans } from "next/font/google";

export const metadata = {
  title: 'Superclean - Mitra Apps',
  description: 'Generated by create-nx-workspace',
};
const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className='scroll-smooth'>
      <body
        className={`${jakartaSans.className} antialiased m-auto max-w-[600px] bg-white dark:bg-black text-black dark:text-white`}
      >
        <ThemeProvider defaultTheme="light" enableSystem={false} attribute="class">
          <ProtectedLayout>
              <Toaster />
            {children}
            <NavigationBar />
          </ProtectedLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
