import '@superclean-workspace/shared/styles';
import { ThemeProvider } from 'next-themes';
import { Figtree } from "next/font/google";
import { Sidebar } from "@shared/components/ui/Sidebar"
import { Navbar } from "@shared/components/ui/Navbar"
import { Breadcrumbs } from "@shared/components/ui/Breadcrumbs"

const fightree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: 'Welcome to admin-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className='scroll-smooth'>
      <body
        className={`${fightree.className} antialiased md:flex`}
      >
        <ThemeProvider enableSystem={true} defaultTheme='system' attribute="class">
          <Sidebar />
          <section className='flex flex-col w-full h-full'>
            <Navbar />
            <Breadcrumbs />
            <main className='w-full min-h-screen overflow-y-scroll px-3 pb-3'>
              {children}
            </main>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
