import '@superclean-workspace/shared/styles';
import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: 'Welcome to admin-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className='scroll-smooth'>
      <ThemeProvider enableSystem={true} attribute="class">
        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
